### ISSUE TITLE
configobj

### ISSUE THREAD

**Issue by jaimebayes** [JGCRI/demeter#15]
Hi, 

I am trying to run the example, but I got this error after import package.
Any advice, 
Thanks, JL

`import os
from demeter.model import Demeter`

/usr/local/lib/python3.6/dist-packages/demeter/config_reader.py in <module>()
     14 import sys
     15 
---> 16 from configobj import ConfigObj
     17 
     18 

ModuleNotFoundError: No module named 'configobj'

**Comment by crvernon** [comment]
Thanks for the feedback @jamiebayes!  It looks like the `configobj` package was somehow removed from our `requirements.txt` file which dictates the package dependencies that need to be installed for Demeter to function.  I will fix this in another branch in a few minutes and resolve this issue in a PR.  Once I pull the changes into the master, you should simply be able to run `git pull --all` in the Demeter directory you cloned to update your master branch.  Alternatively, you can install `configobj` separately using `pip install configobj`.  Just make sure that you are using the version of `pip` that matches your Python installation if you have multiple versions of Python installed.   Just as a note, we plan on releasing Demeter v2 with lots of upgrades soon so stay tuned!
