### ISSUE TITLE
The map function in the output module cannot be used in V1.2.0

### ISSUE THREAD

**Issue by moulai** [JGCRI/demeter#24]
Hello, I am currently trying to migrate from Demeter V1.1.0 to V1.2.0. It is very necessary to migrate the python version to 3.6 and above.
However, although the map function in the output module (such as the map_luc_pft option) is still retained in the config.ini of the example data, I checked the source code and found that the map function has been removed in the V1.2.0 version.
Is the map function permanently removed or just hasn't been added to V1.2.0 yet?
Thank you again for your efforts and hope to get your reply!

**Comment by crvernon** [comment]
Hi @moulai !  The mapping functionality has been removed in v1.2.0 because there are so many easily accessible options for the user to generate custom maps now that were not available when `demeter` was first introduced.  We cut this feature to make maintenance more focused on the functionality of the downscaling algorithms.  I will check on the configuration option to make sure that we remove that from the configuration file.

I am curious, have you been using the mapping features?  

Also, we have a v2 release of demeter that is planned for the coming months that should greatly improve performance and offer the ability to run a single land region at a time and customize parameters per land region.  I would love to hear any feedback on features that you use often!

Thanks so much!

**Comment by moulai** [comment]
> Hi @moulai ! The mapping functionality has been removed in v1.2.0 because there are so many easily accessible options for the user to generate custom maps now that were not available when `demeter` was first introduced. We cut this feature to make maintenance more focused on the functionality of the downscaling algorithms. I will check on the configuration option to make sure that we remove that from the configuration file.
> 
> I am curious, have you been using the mapping features?
> 
> Also, we have a v2 release of demeter that is planned for the coming months that should greatly improve performance and offer the ability to run a single land region at a time and customize parameters per land region. I would love to hear any feedback on features that you use often!
> 
> Thanks so much!

Hello, thanks for your reply!
I often use the map function when using Demeter to have a quick view of the downscaling results. I have many sets of land use scenario data, and I need to see how these scenarios differ in predicting land use quickly and roughly. I agree there are many other ways to visualize the downscaling results. Demeter itself should focus on the downscaling algorithm. I think you deleted the ensemble function because of this consideration.
At the same time, I think it's okay to keep the map function. When a beginner of Demeter is using the example, if he can see the visible result like some maps, he will have a clearer understanding of the operation of the Demeter. Otherwise, he will need to check the format of the data files generated like csv, nc, etc., do visualization work, and then check the results. These cumbersome processes may make him give up the in-depth study and use of Demeter at the beginning.
However, the realization of the map function in v1.1.0 relies on countrycord.csv and regioncord.csv, which is not a proper way of drawing. Perhaps it would be better to use a python library like cartopy.

I also found that you have removed the reference function from v1.2.0, limiting the region partition of the input data to the gcam format. However, my input file is not generated by gcam (but generated by other IAMs), so I manually added the reference function back to v1.2.0. I think you can still retain the reference function so that the Demeter can be applied to other IAMs outputs, and it can also be used by more researchers and in more situations.

I look forward to Demeter v2.0! It is significant to use different parameters in different regions, especially considering that the downscaling patterns in tropical, temperate, and boreal regions may differ significantly. Thank you and your team for your hard work!
