### ISSUE TITLE
MODIS observed data for multiple crops (13 crops) 

### ISSUE THREAD

**Issue by oayounis** [JGCRI/demeter#37]
Hi.. I am trying to run Demeter to downscale land cover for the 13 crops included in GCAM instead for all crops combined. The current data provided with the example files provide the observed land cover on a grid scale for all cropland combined. Is it possible to provide a similar file but with the data for each GCAM crop instead ?

**Comment by kanishkan91** [comment]
@oayounis Could you access the data pointed above? Also, a revised workflow that downscales all crops from demeter is available here- https://zenodo.org/records/10826464. 

Let me know and I can close this issue

**Comment by oayounis** [comment]
I am trying this data now but I noticed that the land cover types in both the observed and projected data are a little different than what I have from GCAM V5.4 (e.g. fruits ,vegetables, Legumes etc are not an output I get from GCAM).  So to use these files, should I aggregate some of these to land cover types myself with land type I get from GCAM (for e.g.  aggregate the shares of fruits and vegetables and lump them with misc. crops)?

**Comment by oayounis** [comment]
Thank you for your response @kanishkan91 !. I am trying this data now but I noticed that the land cover types in both the observed and projected data are a little different than what I have from GCAM V5.4 (e.g. fruits ,vegetables, Legumes etc are not an output I get from GCAM). So to use these files, should I aggregate some of these to land cover types myself with land type I get from GCAM (for e.g. aggregate the shares of fruits and vegetables and lump them with misc. crops)?

**Comment by kanishkan91** [comment]
@oayounis Yes, this was made for GCAM 7 which models many more land types. However you can aggregate the land types as in your version of GCAM with those available in the mapping file- **gcam_regbasin_moirai_v3_type5_5arcmin_projected_alloc.csv** located in the allocation folder. Let me know if that works. That should be the easiest way to get it working.
